# Generated by Django 6.0.3 on 2026-03-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('discount_percentage', models.IntegerField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('is_weekend_offer', models.BooleanField(default=False)),
                ('is_festive_offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dish_images/'),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_combo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/'),
        ),
    ]
