# Generated by Django 4.2 on 2026-03-05 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_address_order_alter_dish_id_alter_offer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='is_festive_offer',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='is_weekend_offer',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='title',
        ),
        migrations.AddField(
            model_name='offer',
            name='code',
            field=models.CharField(default='WELCOME10', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.offer'),
        ),
    ]
