# Generated by Django 4.2 on 2026-03-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_offer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(default='WELCOME10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='is_festive_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_weekend_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.CharField(default='WEEKEND10', max_length=200),
            preserve_default=False,
        ),
    ]
