# Generated by Django 4.2 on 2026-03-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_address_id_alter_cart_id_alter_dish_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(default='WELCOME10', max_length=100),
            preserve_default=False,
        ),
    ]
