# Generated by Django 6.0.3 on 2026-03-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_address_name_address_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
